### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by tmarti2** [nwg-piotr/sway-gtk-menu#36] opened 2020-02-03 13:16 UTC
Hi,
I just found out about your package so I decided to give it a try (I used wofi until now, which is great even if I don't like some features).

I found 2 performance issues :
- with sgtk-dmenu : it is quite slow when you first start to type something (probably because it has to check everthing), is it fixable?
- overall : is there a way to reduce launch time? it is really fast with rofi or wofi (almost instantaneous in fact), but sgtk-menu is longer (less than 0.5sec, but still)

I'll continu to use it, great work !

**Comment by nwg-piotr** [comment] 2020-02-03 13:43
Hi,

This is python, not C, so it'll always be slower.

> with sgtk-dmenu

This command first reads all commands found in your $PATH. The speed depends on how many commands you have installed, and also on your machine performance. On my 5 years old 4 x i7 laptop w/ about 3500 command I have no visible delay.

The `sgtk-menu` command needs about 300 ms to pop up the menu on my machine, and most of them is the time needed to build GUI with pygobject. I see no major possibility to speed it up, except for writing from scratch in C.

> overall : is there a way to reduce launch time?

On sway and i3 - yes. See troubleshooting: [Menu does not position properly in the screen corner](https://github.com/nwg-piotr/sgtk-menu/wiki/Troubleshooting#sway-i3-menu-does-not-position-properly-in-the-screen-corner). Try decreasing the default 100 ms delay down to the value, which works well on your machine (30 ms on my laptop).

**Comment by nwg-piotr** [comment] 2020-02-03 14:17
One more thing: the script will be shorter (and probably faster) as soon, as the overflowed menus issue #1 is fixed. I did hope it to happen together with sway 1.4, but the problem still exists. It may be either sway- or GTK-related, I'm not sure.

**Comment by tmarti2** [comment] 2020-02-03 14:24
Well, I have a Xeon E-2176 and about 4000 command, and it's really slow with a freeze when I start typing.
I guess it can't be faster if python is the problem.
it has nothing to do with the manual, but ok

**Comment by nwg-piotr** [comment] 2020-02-03 14:32
> it has nothing to do with the manual, but ok

To some degree it does, since the default delay is 100 ms, just for security. Try decreasing the value one way or another.

If it's really REALLY slow, the reason is probably different. The problem is: how to reproduce the behaviour. Please tell me more about your environment.

**Comment by tmarti2** [comment] 2020-02-03 14:50
I tried different values between 10 and 100 before posting this issue, and it doesn't really change anything.
For sgtk-menu python is probably the problem, it's fast but not as fast as wofi like I said.
For dmenu, since it's faster as I type new letters, the issue comes from the number of entries. 
I can't really say why it's slow for me and not for you.

**Comment by nwg-piotr** [comment] 2020-02-03 14:57
>  the issue comes from the number of entries

At the moment I'm on VirtualBox w/ 3852 commands, and I see no noticeable slow down...

**Comment by nwg-piotr** [comment] 2020-02-03 15:00
Could you execute `sgtk-dmenu` from terminal and check if any warnings appear? Except for

>  Gtk-WARNING **: 15:58:10.115: no trigger event for menu popup

which is impossible to avoid.

**Comment by tmarti2** [comment] 2020-02-03 15:19
No warning except for the one you mentionned.
4964 commands in $PATH to be exact

**Comment by tmarti2** [comment] 2020-02-03 15:23
I won't use sgtk-dmenu anyway, just sgtk-menu and sgtk-bar, I just wanted to warn about it, but if it's just for me it's not really a problem

**Comment by nwg-piotr** [comment] 2020-02-03 15:26
Thank you very much. One way or another, tonight I'll try to build the menu in a different way.

**Comment by nwg-piotr** [comment] 2020-02-04 19:20
I confirm that searching the first, 1 character long phrase takes more time: about 30% more. After deleting with backspace and entering again, the same phrase is being searched faster. The reason is a mistery to me, as it's just the very same code executed again.

I read through the search method carefully, and optimized it as much as possible, which resulted in speeding up the process of about 15%. However, on my machine it's measurable, but difficult to notice in real life. The most demanding phrase (in my case a single `e` letter gives most results) is being searched in 500 ms - used to be about 600 ms. 2 and more characters long phrases take less than 100 ms, usually about 40. Searching could be sped up of further 10 - 15 ms if it was case sensitive, but the gain would be absolutely unnoticeable, so I left case insensitive, which is more convenient.

All the changes I made have been merged and released as v1.1.3. Also the AUR version is now 1.1.3. I'd be grateful if you please could check what it looks like on your machine.

**Comment by tmarti2** [comment] 2020-02-05 09:23
I didn't noticed a difference, tried to measure it by hand but I got around 0.5s for both version.

**Comment by nwg-piotr** [comment] 2020-02-05 10:38
Provided that you're talking about 1 char long phrase, which gives more 1000 entries long result, it seems it can't be done faster with python and GTK.

**Comment by nwg-piotr** [comment] 2020-02-07 14:19
To summarize: on a decent machine no delay should exceed 0.5 - 06 s. If some of commands works slower for you, feel free to reopen the issue.

**Closed as completed by nwg-piotr** 2020-02-07 14:19 UTC

**Comment by nwg-piotr** [comment] 2020-03-11 08:21
> overall : is there a way to reduce launch time?

Recent discovery: the icon theme strongly affects the time of UI generation. Replacing the custom theme I used to use with stock ePapirus shortened the time needed to generate application grid from 400 to 180 ms on my laptop / sway wm. Even better results (150 ms) it achieves on X11 WMs.
